### PR TITLE
Issue 49822: Pipeline does not show a job as failed if DB fails

### LINKED ISSUE #5336: [LKCRI] Issue 49822: Pipeline does not show a job as failed for if DB fails over to secondary server
[Issue 49822: Pipeline does not show a job as failed for if DB fails over to secondary server](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=49822)

Target Release: 24.3 maintenance release

### Tasks 📍 
- [x] Dev - 5
- [x] Manual Testing - 2 @labkey-danield 
- [x] Code reviews - 1 @labkey-susanh 
- [x] Manual Testing feedback - .5 @labkey-jeckels 
- [x] TC Review and Merge - 1

### PR DESCRIPTION
**Pull request by labkey-jeckels**
#### Rationale
If a pipeline job is running or queued to be run when the database goes down, we fail to update its state in the DB. If the DB later comes back online, the job looks like it's still running or queued. That's inaccurate and can lead to ETLs not being queued on schedule, etc.

#### Changes
- Stash the list of updates that failed
- Check once a minute for failed updates and retry them

### CODE REVIEW

File: pipeline/src/org/labkey/pipeline/api/JobStatusRetryJob.java [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+{
+    private static final Map<String, Runnable> _queuedUpdates = Collections.synchronizedMap(new HashMap<>());
+
+    static
+    {
+        try
+        {
+            Scheduler scheduler = StdSchedulerFactory.getDefaultScheduler();
+
+            // Get configured quartz Trigger from subclass
```
Comment (labkey-susanh) [inline pipeline/src/org/labkey/pipeline/api/JobStatusRetryJob.java]: I'm not understanding how the comment aligns with the code. This doesn't seem to be getting anything from the subclass.

File: pipeline/src/org/labkey/pipeline/api/JobStatusRetryJob.java [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+        }
+    }
+
+    @Override
+    public void execute(JobExecutionContext jobExecutionContext) throws JobExecutionException
+    {
+        // Attempt the updates to the DB rows again in the hopes that the DB is back online
+        synchronized (_queuedUpdates)
+        {
+            if (!_queuedUpdates.isEmpty())
```
Comment (labkey-susanh) [inline pipeline/src/org/labkey/pipeline/api/JobStatusRetryJob.java]: The `if` statement doesn't seem necessary.

File: pipeline/src/org/labkey/pipeline/api/PipelineStatusManager.java [hunk 3]
```diff
@@ -162,84 +163,93 @@ public static boolean setStatusFile(PipelineJob job, User user, PipelineJob.Task
...
     public static boolean setStatusFile(PipelineJob job, User user, String status, @Nullable String info, boolean allowInsert)
     {
-        PipelineStatusFileImpl sfExist = getJobStatusFile(job.getJobGUID());
-        if (sfExist == null && null != job.getLogFilePath())
+        try
         {
-            // Then try based on file path
-            sfExist = getStatusFile(job.getContainer(), job.getLogFilePath());
-        }
+            PipelineStatusFileImpl sfExist = getJobStatusFile(job.getJobGUID());
```
Comment (labkey-susanh) [inline pipeline/src/org/labkey/pipeline/api/PipelineStatusManager.java:168]: I know this was existing code and likely not worth changing now, but the name `sfExist` here is odd to me. `existingFile` would read better to me.

File: pipeline/src/org/labkey/pipeline/api/PipelineStatusManager.java [hunk 4]
```diff
@@ -162,84 +163,93 @@ public static boolean setStatusFile(PipelineJob job, User user, PipelineJob.Task
...
-            sfExist = getStatusFile(job.getContainer(), job.getRemoteLogPath());
-        }
-        PipelineStatusFileImpl sfSet = new PipelineStatusFileImpl(job, status, info);
+            if (sfExist == null && job.getLogFilePath() != job.getRemoteLogPath() && null != job.getRemoteLogPath())
+            {
+                // Check to see if the job is listed under the Remote log file.
+                // This will happen if job was previously run from a cloud root.
+                sfExist = getStatusFile(job.getContainer(), job.getRemoteLogPath());
+            }
+            PipelineStatusFileImpl sfSet = new PipelineStatusFileImpl(job, status, info);
```
Comment (labkey-susanh) [inline pipeline/src/org/labkey/pipeline/api/PipelineStatusManager.java:181]: `sfSet` is also a strange name to me, to the extent that I don't know what a better name is.

File: pipeline/src/org/labkey/pipeline/api/PipelineStatusManager.java [hunk 5]
```diff
@@ -162,84 +163,93 @@ public static boolean setStatusFile(PipelineJob job, User user, PipelineJob.Task
...
-        if (isNotifyOnError(job) && PipelineJob.TaskStatus.error.matches(sfSet.getStatus()) &&
-                (sfExist == null || !PipelineJob.TaskStatus.error.matches(sfExist.getStatus())))
-        {
-            LOG.info("Error status has changed - considering an email notification");
-            PipelineManager.sendNotificationEmail(sfSet, job.getContainer(), user);
-        }
+            else if (PipelineJob.TaskStatus.complete.matches(status))
+            {
+                // Make sure the Enterprise Pipeline recognizes this as a completed
+                // job, even if did it not have a TaskPipeline.
```
Comment (labkey-susanh) [inline pipeline/src/org/labkey/pipeline/api/PipelineStatusManager.java]:
```suggestion
                // job, even if it did not have a TaskPipeline.

```

**Review by labkey-susanh — APPROVED** [review]

File: pipeline/src/org/labkey/pipeline/api/JobStatusRetryJob.java (hunk 1 above)
Comment (labkey-jeckels) [reply pipeline/src/org/labkey/pipeline/api/JobStatusRetryJob.java]: I failed to clean up the comments from the message digest code that I started with. Fixed.

File: pipeline/src/org/labkey/pipeline/api/JobStatusRetryJob.java (hunk 2 above)
Comment (labkey-jeckels) [reply pipeline/src/org/labkey/pipeline/api/JobStatusRetryJob.java]: I restructured the code a bit in my latest comment and the `if` check is a little more useful now. Not vital, but it saves a tiny bit of work

File: pipeline/src/org/labkey/pipeline/api/PipelineStatusManager.java (hunk 5 above)
Comment (labkey-jeckels) [reply pipeline/src/org/labkey/pipeline/api/PipelineStatusManager.java]: Fixed.

File: pipeline/src/org/labkey/pipeline/api/PipelineStatusManager.java (hunk 3 above)
Comment (labkey-jeckels) [reply pipeline/src/org/labkey/pipeline/api/PipelineStatusManager.java:168]: I agree but am opting to keep the diff smaller instead of doing the rename
